# Getting started with Social Psychology

Humans have been described as 'social animals' - it can plausibly be argued that our ability to cooperate in social groups is what sets us apart from our otherwise close animal relatives. This can obviously result in prosperity and beautiful cultural creations, but also in mass violence and destruction. Social psychology attempts to understand how individuals behave in groups, and thus what the conditions are for positive and negative outcomes to arise.

## Video lecture for this week

Once the video lecture is available, it will show here

`r video_code("NOTFOUND")`


You can <a href="./files/Lecture_5_-_critiquing_social_psychology.pptx">download the slides here</a>

## Preparation before class



## Recommended readings

* Textbook: [Chapter 1](https://open.lib.umn.edu/socialpsychology/part/chapter-1-introducing-social-psychology/) and [Chapter 2](https://open.lib.umn.edu/socialpsychology/part/chapter-2-social-learning-and-social-cognition/) in *Principles of Social Psychology*

* Further (non-academic) reading: *Humankind* by Rutger Bregman is a beautiful book that draws on social psychology and related disciplines to argue that humans are fundamentally good. It provides a novel perspective on many 'landmark' research findings and offers hope in these troubled times.

