# Prejudice and intergroup conflict

Understanding intergroup conflict has been a priority from the start of social psychology, in the aftermath of World War II. This week, we are exploring how prejudice emerges, how it shapes relationships between groups on many levels and it can be reduced.

## Video lecture for this week

This week's lecture is split into four parts, that you should watch in order. In between, there are a couple of questions that will allow you to reflect on the content and make sure you have understood the main points.

You can download the lecture slides <a href="./files/Lecture_2_-_self__social_identity_and_prejudice.pptx">here</a>

### Emergence of prejudice

`r video_code("QQeC6n2mtsk")`

Before you move on, take a moment to reflect on the content of the video and answer the following questions:

* According to Social Identity Theory, how do we most want to view groups that we belong to: `r mcq(c("fair and welcoming", answer = "positively distinct", "dominant and powerful"))`
* Match the following concepts to affect, behaviour and cognition:
    + prejudice: `r mcq(c(answer = "affect", "behaviour", "cognition"))`
    + stereotypes: `r mcq(c("affect", "behaviour", answer = "cognition"))`
    + discrimination: `r mcq(c("affect", answer = "behaviour", "cognition"))`
* What is the availability heuristic? Think about the answer before viewing it.
`r hide("View answer")`
The tendency to use availability - the ease with which one can bring to mind exemplars of an event - as a way to estimate the probability or frequency of that event. 
`r unhide()`

    
### Maintaining false beliefs

`r video_code("dCSQwC6Zcmk")`

* According to Leon Festinger, what mental state do we want to avoid? `r fitb("cognitive dissonance", ignore_case = TRUE)`
* What type of information do people generally seek out most? Information that `r mcq(c("allows them to test and develop their beliefs", answer = "confirms their belief", "has the highest quality"))`
* Test your estimates of immigration to your local area in the UK (note that the numbers are from 2014, but you can still see if you are way off) `r hide("View test")`
<iframe height="550px" width="100%" src="https://www.ons.gov.uk/visualisations/nesscontent/dvc278/quiz/index.html"></iframe>
`r unhide()`

### Impact of prejudice and stereotypes

`r video_code("n82z9C55JeI")`

* Optional: take an Implicit Association Test to learn more about your personal views and to see how implicit bias is measured: [Project Implicit](https://implicit.harvard.edu/){target="_blank"}
  
### Reducing prejudice and promoting inclusion

`r video_code("-njSO-fsszc")
`
* Can you think of any personal examples where some kind of intergroup contact changed your attitudes? If so, how did that change come about?
* True or false: telling people to ignore group memberships in evaluating individuals (i.e. to be 'colour-blind') leads to better intergroup outcomes than promoting multiculturalism. `r torf(FALSE)` 
* What is a meta-analysis? Think about the answer before viewing it.
`r hide("View answer")`
A study that collects all research (ideally published and unpublished) on a given topic and then statistically combines their results. This gives us the best evidence whether there really is an effect and how strong the effect is likely to be, because random error and variation across studies should cancel out. 
`r unhide()`

## Recommended readings

* Textbook: [Chapter 12](https://open.lib.umn.edu/socialpsychology/part/chapter-12-stereotypes-prejudice-and-discrimination/) in *Principles of Social Psychology*
* Chapter 9 in **Social Psychology: Revisiting the classic studies** (about Sherif & Sherif's summer camp study) 
* Chapter 10 in **Social Psychology: Revisiting the classic studies** (about Tajfel's minimal group studies - best read *after* class) 
    + After you have read about Tajfel's minimal group experiments (e.g., this Chapter 10), have a look at a recent paper that makes some important points regarding the limits and the interpretation of these findings: [@sand2020gentle]




