# Social influence: behaviour in groups

We spend much of our lives in groups - be they groups of friends hanging out, teams trying to 
achieve a common purpose or protestors working to bring about change. Often, our individual
behaviour is powerfully shaped by the presence of others. This week, we will explore when 
that happens, and how groups can enhance rather than impede both performance and moral behaviour.

## Video lecture for this week

This week's lecture is split into five parts, that you should watch in order (if you run out of time or patience, the fifth part is optional). In between, there are a couple of questions that will allow you to reflect on the content and make sure you have understood the main points.

You can download the lecture slides <a href="./files/Lecture_3_-_group_influences_and_group_behaviours.pptx">here</a>.


### Social facilitation & social loafing

`r video_code("JnMjhEEbvzo")`

Before you move on, take a moment to reflect on the content of the video and answer the following questions:

* According to the social facilitation effect, how does the presence of others affect one's performance? `r mcq(c("It improves performance",  "It decreases performance", answer = "Can be either - strengthens the 'dominant' response"))`
* Think back to a time when you successfully completed a group project. Was there any social loafing going on? If so, how did you deal with it? If not, what do you think prevented it?

### Deindividuation

`r video_code("Z5PyGqNuLH4")`

Before you move on, take a moment to reflect on the content of the video and answer the following questions:

* Can you explain the social identity account of deindividuation? Can you think of a personal example where deindividuation led to you behaving in a way that was strongly in line with group norms?
* In Diener's (1976) trick or treat experiment, the experimenters manipulated whether or not participants were anonymous. They just observed whether participants arrived alone or in groups. Which of their two main conclusions is based on better evidence, based on that design? `r mcq(c(answer = "Anonymity increases transgressions",  "Being in a group increases transgression", "No difference"))` (If you are not confident in your answer, please make sure to bring this up in class.)

### Group behaviours

`r video_code("PwmJ_GrfAUE")`

Before you move on, take a moment to reflect on the content of the video and answer the following questions:

* What effect are online 'echo chambers' most closely related to? `r mcq(c("Group convergence",  answer = "Group polarisation", "Groupthink"))`
* Can you think of any situations - in your personal life or in history - when groupthink led to a wrong decision being taken? If you were involved in that decision making process (again), what steps would you take to prevent groupthink?
* A controversial application of the ideas of group convergence and group polarisation comes from the "costly signaling" explanation for religious beliefs and behaviours. If you are curious about that, have a look at the section on [Wikipedia](https://en.wikipedia.org/wiki/Signalling_theory#Religion_as_a_costly_signal){target="_blank"}. Then consider whether you find the idea convincing (based on that very limited knowledge about the research evidence) and how it relates to the concepts we have discussed so far. 

### Social influence

`r video_code("02mVEJOtBOE")`

Before you move on, take a moment to reflect on the content of the video and answer the following questions:

* Let's briefly think about antisemitism and the holocaust. What is going on in the following situations, and what kind of institutional or educational interventions could reduce the likelihood of that type of behaviour?
    + someone hears throughout their life that Jews are bad and dangerous, comes to share that belief and joins in the destruction of Jewish shops etc: `r mcq(c(answer = "Conformity", "Compliance", "Obedience"))`
    + a guard in a concentration camp send Jews to the gas chambers because they have been given the order to do so: `r mcq(c("Conformity", "Compliance", answer = "Obedience"))`
    + someone stops seeing their Jewish friend because they do not want to face any disapproval from their (much larger) group of German friends: `r mcq(c("Conformity", answer = "Compliance", answer = "Obedience"))`

### Bonus: Milgram's shock machine experiments

`r video_code("2rIQRQYeZMs")`

Before you move on, take a moment to reflect on the content of the video and answer the following question:

* Do you believe you would have gone all the way up to 450V if you had participated in the experiment? How confident are you in your answer? If you think you would have resisted, what strategies would you have employed?


## Preparation before class

Make sure to watch the videos and engage with the questions. This week, in particular, you should be able to connect all the theoretical concepts to your own life experiences, which can make them more memorable and likely also help you in life beyond this module.


## Recommended readings

* Textbook: [Chapter 7](https://open.lib.umn.edu/socialpsychology/part/chapter-7-influencing-and-conforming/) and [Chapter 11](https://open.lib.umn.edu/socialpsychology/part/chapter-11-working-groups-performance-and-decision-making/) in *Principles of Social Psychology*

* Chapter 7 in **Social Psychology: Revisiting the classic studies** (and chapter 5 and 6, if you have time). Additionally, you can read Chapter 8 in **Humankind**, especially if you are considering writing the essay on Milgram.

* Review article on how to create social norms that promote pro-environmental behaviour [@cialdini2003crafting]. Beyond that particular issue, 
this shows how social influence can be used for good.


