
# Study Skills 1: Planning & reading

Starting at university is all about taking charge of your own learning. In this seminar, we will discuss some strategies for doing so, and for dealing with the risk of information overload.

## Seminar materials

You can download the slides <a href="./files/Seminar_1_-_planning__reading_etc.pptx">here</a>. You do not need to look at them before the seminar, but they contain useful reference materials and links for later on.


## Preparation before class

- Link Google Scholar to your St Mary's account - [check here for instructions](#read)
- Download the following article, either from the journal webpage (might need to log in through the library) or through [this open access link](http://faculty.missouri.edu/segerti/capstone/ArielyCounterfeitSelf.pdf){target="_blank"} 
Gino, F., Norton, M. I., & Ariely, D. (2010). The counterfeit self: The deceptive costs of faking it. **Psychological Science**, **21**(5), 712-720.


## Recommended readings and further resources

- Article on the LSE student blog on *note taking in lectures* - almost all points apply to online lectures as well. [Click here](https://info.lse.ac.uk/current-students/Assets/Articles/10-Tips-on-note-taking-during-lectures){target="_blank"}
- Article on *reading social psychology journal articles* [Click here](https://www.uvm.edu/~dguber/POLS234/articles/read.htm){target="_blank"}. verywellmind offers a shorter, more superficial take on the same topic. [Click here](https://www.verywellmind.com/how-to-read-and-understand-a-psychology-journal-article-2795709){target="_blank"}.   
