# (PART\*) Additional information {-}

# Assignment

This module will be assessed with a workbook (40%) and a portfolio (60%) assessment. The workbook consists of two multiple choice tests, while the portfolio consists of a 1,500 word essay, which we will develop step-by-step.

## Workbook

After each section of the course (social & developmental), you will take an online multiple choice test. These tests each consist of 35 questions and contribute 20% to your final mark. You can find the deadlines and further details on [Moodle](https://mymodules.stmarys.ac.uk/course/view.php?id=28580#section-3){target="_blank"}

## Portfolio

We will use the portfolio to work on your essay writing skills in several steps. You will first create an essay plan that you will receive a grade and feedback for, then write an introduction and peer-review some, and then finally write a full essay.

**<a href="./files/PSY_4013_2020_Portfolio_Instructions.pdf">Click here</a>** for full instructions and submit your work on [Moodle](https://mymodules.stmarys.ac.uk/course/view.php?id=28580#section-6){target="_blank"}





